### ISSUE TITLE
2021.12.21 Tue

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/weekly-retrospective#41]
### 집
total 65min
- [x] 15min 피아노
- [x] 10min 독서
- [x] 15min dev - react 번역
- [x] 10min 알고리즘
- [ ] 10min meditation
- [x] 5min 재테크 공부

**Comment by AnneMayor** [comment]
@wooooooood 응원합니다 니키님!오늘 꼭 다 하시길!!!

**Comment by wooooooood** [comment]
* [ ]  15min 피아노
 * [ ]  10min 독서
 * [ ]  15min dev - react 번역
=> https://github.com/reactjs/ko.reactjs.org/issues/374 에 번역 신청한 것.. 생각보다 길고 고려해야할 것도 많구나 ^^;
 * [ ]  10min 알고리즘
 => 생각해보니 지금 알고리즘을 할 때가 아니라서 위에 react 번역에 25min을 썼다.
 * [ ]  10min meditation
=> Headspace appreciation
 * [x]  5min 재테크 공부
=> 버스에서 경제 뉴스레터 어피티 밀린거 읽음. 인상적인건 올 해에 미국 REITS 주가 많이 올랐는데 내년에도 오를 거라는 전망😏

**Comment by AnneMayor** [comment]
👍 굳굳 그래도 계획한대로 실천하시는 모습이 저도 정신차리게 되네요
