### ISSUE TITLE
Goal of this RT season (Jan)

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/weekly-retrospective#44]
### What?
- practice speaking English **everyday** and organize knowledge with posting at blog once a week

### HOW?
- 1 news, 1 post a week 
- Will and learn new vocas with [NPR](https://www.npr.org/) because NPR provides mp3 and script!
- But practice speaking everyday (=1주일에 기사 1개를 완전하게 씹고 뜯고 맛보고 즐기는거임)
- 새해 버프로 한 달은 하지 않을까 예상함

### Daily practice tracker
- [ ] 1
- [x] 2
- [x] 3
- [x] #50
- [x] 5
- [x] 6
- [x] 7
- [ ] 8
- [ ] 9
- [x] 10
- [x] 11
- [x] 12
- [ ] 13
- [ ] 14
- [ ] 15
- [x] 16
- [x] 17
- [ ] 18
- [ ] 19
- [x] 20
- [ ] 21
- [ ] 22
- [x] 23
- [ ] 24
- [ ] 25
- [ ] 26
- [ ] 27
- [ ] 28
- [ ] 29
- [x] 30
- [ ] 31

**Comment by AnneMayor** [comment]
Will monitor this issue. Go for it 👍

**Comment by wooooooood** [comment]
**day2**. selected [Facebook bans 7 'surveillance-for-hire' companies that spied on 50,000 users](https://www.npr.org/2021/12/16/1064628654/facebook-bans-surveillance-firms-that-spied-on-50000-people) 
practice. 

- surveillance firm; 감시 회사
- correspondent; 1. (특정 지역이나 주제 담당) 기자, 특파원

**Comment by wooooooood** [comment]
day3. Man speaks really fast
day4. Sickㅠㅠ - Skip
day5. 
**단어**
- mercenary: 돈을 목적으로 하는
- infilterate: 침투시키다
- befriend: -의 편을 들다, 친구가 되다
- lawsuit: 소송, 고소
- crackdown: 단속, 탄압
- accuse: 비난하다, 폭로하다

**발음/속도**
through 
so that they could reach out to

**Comment by AnneMayor** [comment]
Could I ask you what type of articles or videos you are watching? Is it tech news?

**Comment by wooooooood** [comment]
> Could I ask you what type of articles or videos you are watching? Is it tech news?

For now, this -> https://www.npr.org/transcripts/1064628654
Tech-Business I guess ㅎㅎ

**Comment by wooooooood** [comment]
day6. 
- impose: 부과하다, 떠맡기다
- sanction: 제재, 인과
- autocrat: 독재자
- dictator: 독재자, 권력자
- norm: 표준, 규범
- authoritarian: 권위주의의, 독재주의의

**Comment by AnneMayor** [comment]
For me, your English words is more like being used in News especially huge accidents 😂

**Comment by wooooooood** [comment]
블로그에 작성을 하고 나니 그 뒤로는 놀아버리는 사태가..^^;
day 10. selected new => [We may be one step closer to storing data in DNA](https://www.npr.org/transcripts/1061028439)

**Comment by wooooooood** [comment]
day 11. changed news => [< China Removed Didi From App Stores, Accused The Company Of Violating Security Rules](https://www.npr.org/transcripts/1015371400)

**Comment by TORU0239** [comment]
> For me, your English words is more like being used in News especially huge accidents 😂

words 'are' haha.

**Comment by TORU0239** [comment]
> day3. Man speaks really fast day4. Sickㅠㅠ - Skip day5. **단어**
> 
> * mercenary: 돈을 목적으로 하는
> * infilterate: 침투시키다
> * befriend: -의 편을 들다, 친구가 되다
> * lawsuit: 소송, 고소
> * crackdown: 단속, 탄압
> * accuse: 비난하다, 폭로하다
> 
> **발음/속도** through so that they could reach out to

infilterate -> infiltrate :)  a synonym of 'penetrate'
I guess u have done well, meanwhile you might want to find some synonym and acronym when learning vocabulary!

**Comment by AnneMayor** [comment]
> > For me, your English words is more like being used in News especially huge accidents 😂
> 
> words 'are' haha.

Thanks for correcting my english!

**Comment by wooooooood** [comment]
> * infilterate

Nice feedback Thank youuu!! 😁

**Comment by wooooooood** [comment]
day 16.
Need to practice more with this news..^^;
- wade: (물 속을)걸어서 건너다, (진창, 눈 따위 걷기 힘든 곳을)간신히 지나가다
- holistic: 전체적인
- encompass: 에워싸다
- raft: 뗏목
- misgiving: 의심
- enact: 제정하다
- compliant: 준수
- class action lawsuit: 집단 소송

**Comment by deveeni** [comment]
There's a lot of words that I heard the first time.  😇

**Comment by TORU0239** [comment]
> day 16. Need to practice more with this news..^^;
> 
> * wade: (물 속을)걸어서 건너다, (진창, 눈 따위 걷기 힘든 곳을)간신히 지나가다
> * holistic: 전체적인
> * encompass: 에워싸다
> * raft: 뗏목
> * misgiving: 의심
> * enact: 제정하다
> * compliant: 준수
> * class action lawsuit: 집단 소송

compliance  is a noun, but compliant is an adjective. :)

**Comment by wooooooood** [comment]
Last news would be Microsoft's M&A

https://www.npr.org/transcripts/1073763644

**Comment by AnneMayor** [comment]
For now, it's February. Will close this issue.
