### ISSUE TITLE
1st personal sprint of Jan 2021 

### ISSUE THREAD

**Issue by TORU0239** [ready-techie/weekly-retrospective#47]
###  Objective 
- Kickoff and warmup 
- Starting Flutter / SwiftUI, to get used to the **declarative UI**

### 🎯 What did I Do?

- [x] 3 : Removing transitive dependency that causes risk findings (Lint), starting first Flutter Project
- [x] 4 : Struggling with Gradle dependency under secured network
- [x] 5 : Created a new branch for What I learnt. (Honestly wanted to put logs into Github history. haha)
- [x] 6 : Birthday, but busy. :( and digital token made me unhappy, plus forgot to write my work down.
- [x] 7 : Decided to get rid of DataBinding with keeping ViewBinding but scanning tool was down!!!
- [x] 8 : Created a new repository for vulnerability scanning tool (open source, named OWASP)
- [x] 9 : Not that much things, applied and tested OWASP but unsure whether removing data binding works on the project.
- [ ] 10
- [ ] 11
- [x] 12 : Debuggable has to be false in Release build in `build.gradle` app level.
- [x] 13 : Which is easier, just writing a code or staying in tons of discussions and documenting?
- [x] 14 : Thought: Have to talk with DevOps team with regard to troubleshooting Fastlane
- [x] 15 : New translation has come! just kicked off
- [x] 16 : Retro day

###  🏄 What went WELL?
- Although there are some empty grass, but luckily managed to commit almost everyday
 
###  🏄 What went NOT WELL?
- No time to do regarding Android or Flutter, is it because I have not been motivated or couldn't find anything interesting?
 
### 🤨 What could have gone BETTER?
- Initiate something regarding what I want to learn!
- form the real code snippet from the obscure idea
 
### 🧐 What did I LEARN?
- Could figure out how to exclude Gradle dependencies after all is loaded (but copy and paste...)
- Vulnerability checking by using some open source

**Comment by AnneMayor** [comment]
Will monitor this issue often haha. Keep it cool 😎

**Comment by AnneMayor** [comment]
I am also curious about OWASP open source. Could you prepare for this issue as your presentation?

**Comment by TORU0239** [comment]
> I am also curious about OWASP open source. Could you prepare for this issue as your presentation?

Of course but it's likely to be introductory for 5 mins since it also takes time for us to run through all the things about OWASP

**Comment by TORU0239** [comment]
Done the first biweekly retro!

**Comment by AnneMayor** [comment]
For sure! Will close this issue. Great job!
