### ISSUE TITLE
2nd personal sprint of Jan 2021 

### ISSUE THREAD

**Issue by TORU0239** [ready-techie/weekly-retrospective#52]
###  Objective
- Beginning the spilt task, Flutter / SwiftUI, to get used to the **declarative UI**
- Complete the translation asap and have it reviewed, to submit by 24

### 🎯 What did I Do?

- [ ] 17 : 
- [x] 18 : Felt the needs understanding the purpose and root of work. (not technically but also business manner)
- [ ] 19 :
- [x] 20 : It's not easy that understanding the structure of sources, esp made by others.
- [x] 21 : Updated InstallReferrer sample but haven't run properly
- [x] 22 : Lightning talk at GDG Incheon (remote, regarding vulnerability) 
- [x] 23 : Anticipated thing came true. 
- [x] 24 : Sick leave. and submitted the PR for blog translation
- [ ] 25 :
- [ ] 26 :
- [x] 27 : What should I ask to the candidate well? importance of question set for interview.
- [x] 28 : Being away from real squad task will be good to me and my squad?
- [ ] 29 :
- [ ] 30 :

###  🏄 What went WELL?
- Not everyday though, but keeping the daily commit (2 ~ 4 times a week)  

###  🏄 What went NOT WELL?
- Too many commits on Markdown file rather than real programming
- Haven't started Flutter and Dart course in Udemy

### 🤨 What could have gone BETTER?
- Hmm.. Should change the format of retro here, other than daily task
 
### 🧐 What did I LEARN?
- Nothing, Still stuck at the same stage. :(

**Comment by wooooooood** [comment]
Niceeeee to see new sprint 🙌 good luck

**Comment by AnneMayor** [comment]
Go for it! I believe you can find your way of work 😄
