### ISSUE TITLE
2022.01.23 (2022년 3주차)

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/weekly-retrospective#53]
### 🎯 What did I Do?
- 평일: 주로 독서, RT 준비.. 스케줄러를 봤는데 정말 한 게 없다. 인스타 중독이었던듯 ㅎㅎ;
- 주말: 엑셀/루틴 책을 읽고 내게 필요한 엑셀 시트와 루틴을 만들어봤다. 

### 🏄 What went WELL?
- 원래 작년 연말에 하려고 미뤄둔 엑셀 시트 정리..
- 집안일할때 경제 라디오를 들었다.
### 🤨 What could have gone BETTER?
- web dev 환경설정 등등의 기술 부채가 쌓여있는걸.. 해결해야 한다..ㅠㅠ (2주째)
- 사실 개선되어야 할 건 너무 많다..
### 🧐 What did I LEARN?
- 프로그래머, 철학을 만나다 :독서
  - 명상과의 공통점은 `현재`에 집중하는 것
  - 고민을 깊게, 충분히 하고 그 뒤로는 실행만 할 수 있도록 하라고 함
- 나를 바꾼 기록 생활 :독서
  - 요즘에는 자신이 얻은 부의 정당성(?) 증명을 생산성 전시를 통해서 한다고 한다. (ex. 애플 ceo 팀쿡은 3:45am인가에 일어난다고 함 ㄷㄷ) 이게 왠지 엄청 인상깊었음
- `루틴`: 관련 책을 빌려서 앞에 조금만 읽었지만 일단 내 루틴을 먼저 정해봄. 그리고 지난 RT에서 들은대로 뇌를 위해 11시에 자고 6시에 일어나는 생활을 계획.
- 내게 있어 시간관리의 핵심은 `우선순위`를 따르는 것임.. 이거의 실천이 필요함. 나는 너무 미뤄서 ㅠㅠ
- 예전에 빈님이 공유해주신 회고에서, `잘되든 안되든 **분 실행` 이라는걸 보고 따라하고 있는데 만족스럽다. 다만 그 실행 자체를 미루지 않도록 해야할듯
### 👀 TODO
- (요즘 유행하는) 미라클 모닝 1H => 해보고 나한테 맞는지..
  - 명상, 요가
  - 주식 공부
- 저녁: 운동, 알바, 독서, 기술부채 정리 2H

**Comment by AnneMayor** [comment]
> - web dev 환경설정 등등의 기술 부채가 쌓여있는걸.. 해결해야 한다..ㅠㅠ (2주째)

이건 니키님이 개인적으로 느끼시는 기술부채이신가요 아니면 회사에서 가지고 있는 이슈인가요?

**Comment by wooooooood** [comment]
> > - web dev 환경설정 등등의 기술 부채가 쌓여있는걸.. 해결해야 한다..ㅠㅠ (2주째)
> 
> 
> 
> 이건 니키님이 개인적으로 느끼시는 기술부채이신가요 아니면 회사에서 가지고 있는 이슈인가요?

음 둘다인거같아요!! ㅋㅋㅋ 회사에서 개발을 더많이하고 시간에 쫓기면서 하니까 회사내용이 더많긴하네용 ㅠ,ㅠ
