### ISSUE TITLE
30. Jan. 2022

### ISSUE THREAD

**Issue by TORU0239** [ready-techie/weekly-retrospective#57]
30. Jan. 2022 to 6 Feb 2022

### 🎯 What did I Do?
* Had 3 screening calls with recruiters, a role as a sr. developer, the rest for developer advocate and tech evangelist
* Lunar New Year Season!
* Started refactoring for the repository layer
* My translation has been merged. 

###  🏄 What went WELL?
* Became Android Lead Developer haha... 😅
* Still in progress though, but refactoring seems to have run well.

### 🤨 What could have gone BETTER?
* Tried to fix issues in Jenkins Pipeline but didn't work well
* Should have to focus on code level more
* What problem set would be good to ask? 

### 🧐 What did I LEARN?
* Nothing much from my work, but feels the necessities of proper architecture that can be applicable to other projects

**Comment by AnneMayor** [comment]
Wow I am curious how it was haha Any applicant that you wanna work with?

**Comment by wooooooood** [comment]
niceee how was it?? 😀

**Comment by TORU0239** [comment]
Screening call is nothing, but just checking my background and reason why I am looking out new opportunities

**Comment by TORU0239** [comment]
This is weekly retrospective haha..

**Comment by AnneMayor** [comment]
Oh, Sorry I thought this is for last week 😅

**Comment by TORU0239** [comment]
Retro completed!
