### ISSUE TITLE
~2/15 평일 dev 역량강화

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/weekly-retrospective#58]
2월의 일부가 이미 어느정도 지났지만 2/15까지의 sprint 계획을 세운다.
이번 목표는 평일 저녁 개발 학습 루틴을 만들고 실천하고 수정해보는 것이다!
각 최소 10분씩 실행하면서 _얼마나_ 하느냐보다는 **하는 것**에 초점을 맞추고 습관화

| **Day** | **개발(구현)** | **개발 공부(책/인강)** |
|--:|:--:|:--:|
| 3                      |                     |                  웹을 지탱하는 기술 독서|
| 4                              |        side - react timer issue    |     Clean Code chap12 다읽었                   |
| 7                                 |                         |   웹을 지탱하는 기술 독서  |
| 8                                   |                       |     웹을 지탱하는 기술 독서.. 했는데 10분 미만   |
| 9                           |                         |                         |
| 10                           |                         |                         |
| 11                           |                         |                         |
| 14                          |                         | article - react hooks UseMemo, UseCallback 완전하게 이해하진 못함 |
| 15                           | 새컴을 사서 셋업만 계속..  |    웹을 지탱하는 기술 독서.. 빨리 읽고 반납하고싶다 ㅎ     |

**Comment by AnneMayor** [comment]
Go for it! Will keep an eye on it 😄

**Comment by wooooooood** [comment]
후기: 계속..해야겠다...
