### ISSUE TITLE
6 Feb 2022 

### ISSUE THREAD

**Issue by TORU0239** [ready-techie/weekly-retrospective#61]
### 🎯 What did I Do?
1. Fastlane configuration in the local machine to check internal testing track
2. Screening call with a company
3. Simulating the whole flow of app distribution from setting up the app details in console
4. Made a repo to test modern android features
5. Started subscribing Medium as a premium user

###  🏄 What went WELL?
1. Installing CI/CD configuration was successfully set up in my local machine

### 🤨 What could have gone BETTER?
1. Not easy to manage the project alone of course, but still a lot of obstacles to overcome
2. How can I get motivated on other languages and frameworks? it's hard to get for myself hmm
 
### 🧐 What did I LEARN?
1. Trying fastlane commands that may be helpful in the future

**Comment by AnneMayor** [comment]
I will close this issue since it seems you have already reflected. You can reopen this issue if you need 😃

**Comment by TORU0239** [comment]
Reopened and closed.
