### ISSUE TITLE
2022.05.22 🤔

### ISSUE THREAD

**Issue by AnneMayor** [ready-techie/weekly-retrospective#82]
### 🎯 What did I Do?
- 코틀린 학습 
- YAPP 프로젝트 아키텍처 구성(ERD)
- 소프트웨어 아키텍처101 학습

###  🏄 What went WELL?
- YAPP 프로젝트 시작을 드디어 하게 되었다...!
- 이펙티브 코틀린 + 코틀린 인 액션으로 코틀린 감을 잡아가고 있음!

### 🤨 What could have gone BETTER?
- [ ] 체력관리 💪 이번주부터 새로운 헬스장에서 PT를 시작했는데 몸이 적응이 필요한가보더라ㅠ공부까지 하려니 죽을 맛 ☠️
- [ ] 알고리즘 문제풀이 확보 실패ㅠㅠ자꾸 스터디 참석 준비를 못한 상태에서 가게 된다ㅠㅠ
- [ ] 스터디 모임 준비도 착실하게 하도록 하자ㅠ

### 🧐 What did I LEARN?
- 수요일 진짜 컨디션 완전 꽝...그때 정말 내가 얼마나 피곤했는지 화요일에 YAPP 회의 끝나고 들어가는데 잠을 잘 못자겠더라...눈을 감고 잠이 들라하면 막 갑자기 숨소리가 거칠게 들리면서 잠이 깰 정도였음... 😭
- 금요일은 또 왤케 놀고 싶은지 몰겠네...ㅇㅅㅇ약간 업무 시간에 정신이 붕 뜬 느낌이 없지 않았다... 조절 잘하자 💪

**Comment by wooooooood** [comment]
우왕 PT!! 건강 잘 챙기셔요ㅠㅠ!!
